<ul class="breadcrumb">
    <li class="active">Пользователи</li>
</ul>
<div class="row-fluid">
    <div class="span8">
        <table class="table table-hover">
        <thead>
        <tr>
            <th>id</th>
            <th>email</th>
        </tr>
        </thead>
        <tbody id="users">
        <?php
            foreach( $d['users'] as $user ){
                $editPrivileges = $p['auth']->can( \Cerceau\Data\User\Privileges::EDIT_USERS )
                    ? '<a href="/'. $Url->page( 'admin\\Users', 'userPrivileges', $user )
                        .'" class="-privileges-">привилегии <i class="icon-edit"></i></a>'
                    : '';

                echo <<<HTML
        <tr>
            <td>{$user['admin_id']}</td>
            <td>{$user['email']}</td>
            <td>
                <span class="pull-right">$editPrivileges</span>
            </td>
        </tr>
HTML;
            }
        ?>
        </tbody>
        </table>
    </div>
    <div class="span4">
        <?php if( $p['auth']->can( \Cerceau\Data\User\Privileges::ADD_USERS )): ?>
        <form action="/<?= $Url->form( 'admin\\Users' , 'addUser' ) ?>" id="formAddUser" method="post">
            <fieldset>
                <legend>Добавить пользователя</legend>
                <div class="control-group -email-">
                    <label class="control-label">E-mail</label>
                    <div class="controls">
                        <input type="text" name="email" class="input-xlarge" />
                        <span class="help-inline -error-"></span>
                    </div>
                </div>
                <div class="form-actions">
                    <input type="submit" class="btn btn-primary" value="Добавить" />
                </div>
            </fieldset>
        </form>
        <?php endif; ?>
    </div>
</div>


<div class="modal hide fade" id="privilegesEditModal">
    <form action="#" method="post" id="privilegesEditForm" class="modal-form">
        <div class="modal-header">
            <h3>Привилегии пользователя <span id="privilegesEditUserName"></span></h3>
        </div>
        <div class="modal-body">
            <fieldset>
                <ul class="unstyled">
                    <?php
                        $allPrivileges = \Cerceau\Data\User\Privileges::names();
                        $groups = \Cerceau\System\Registry::instance()->I18n()->pick( 'privileges', 'groups' );
                        foreach( $allPrivileges as $privilegeId => $privilegeName ){
                            if( array_key_exists( $privilegeId, $groups ))
                                echo '<legend>'. $groups[$privilegeId] .'</legend>';
                            echo <<<HTML
                    <li>
                        <label for="privileges$privilegeId" class="checkbox">
                            <input type="checkbox" name="privileges[]" id="privileges$privilegeId" value="$privilegeId" />
                            $privilegeName
                        </label>
                    </li>
HTML;
                        }
                    ?>
                </ul>
            </fieldset>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">Отменить</a>
            <input type="submit" class="btn btn-primary" value="Применить" />
        </div>
    </form>
</div>
