<head>
    <meta charset="utf-8" />
    <title>
        <?= empty($p['title']) ? '' : $p['title'] .' * ' ?>
        <?= empty($p['main_title']) ? '' : $p['main_title'] ?>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <?php if(isset($p['keywords'])): ?>
    <meta name="keywords" content="<?= implode( ', ', $p['keywords'] ) ?>" />
    <?php endif; ?>
    <link rel="shortcut icon" href="/img/favicon.png" sizes="16x16">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <?= \Cerceau\Config\Assets::css() ?>
    <!-- IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
